In [1]:
import psycopg2
from datetime import timedelta
from sqlalchemy import create_engine
import psycopg2
import pandas as pd

In [2]:
MIN_WINDOW_LENGTH = 48

## Read in data
Prerequisites:
1. Build postgres-functions (\i path_to_file/postgres-functions.sql)
2. Build flicu_icustay_detail (\i path_to_file/flicu_icustay_detail.sql)
3. Build pivoted_vital (\i path_to_file/pivoted_vital.sql)
4. Build flicu_pivoted_lab (\i path_to_file/flicu_pivoted_lab.sql) (alternatively, build pivoted_lab if lab values before ICU admission are needed)

In [3]:
# Connect to db
#conn = psycopg2.connect(host='localhost', port=5433, dbname='mimic', user='postgres', password='postgres')
conn = psycopg2.connect(dbname='mimic', user='postgres')
cur = conn.cursor() 

# Read in table with patients & admissions (inner join on subject_id) and icu_stays (inner joinon subject_id and hadm_id)
icustay_details = pd.read_sql_query("SELECT * FROM mimiciii.flicu_icustay_detail;", conn)

# Read in vital signs
pivoted_vital = pd.read_sql_query("SELECT * FROM mimiciii.pivoted_vital;", conn)

# Read in lab measurements
# Use flicu_pivoted_lab (as it only takes the lab tests during ICU stay)
#query = "SELECT * FROM mimiciii.flicu_pivoted_lab;"
# Alternative:  Use the lab values recorded previous to the ICU stay (although during same hospital admission!), 
# then sample them  (8h intervalls) and then forward fill plus cap at either icu admission time of first vital sign recorded
query = "SELECT * FROM mimiciii.pivoted_lab;"
pivoted_lab = pd.read_sql_query(query, conn)

# Close the cursor and connection to so the server can allocate bandwidth to other requests
cur.close()
conn.close()

/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(


In [4]:
print(icustay_details.info())
print(icustay_details.head(3))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61051 entries, 0 to 61050
Data columns (total 23 columns):
 #   Column                       Non-Null Count  Dtype         
---  ------                       --------------  -----         
 0   subject_id                   61051 non-null  int64         
 1   hadm_id                      61051 non-null  int64         
 2   icustay_id                   61051 non-null  int64         
 3   gender                       61051 non-null  object        
 4   dod                          23889 non-null  datetime64[ns]
 5   admittime                    61051 non-null  datetime64[ns]
 6   dischtime                    61051 non-null  datetime64[ns]
 7   los_hospital                 61051 non-null  float64       
 8   admission_age                61051 non-null  float64       
 9   ethnicity                    61051 non-null  object        
 10  ethnicity_grouped            61051 non-null  object        
 11  hospital_expire_flag         61051 non-nu

TEST: It should be 46428 patients and 61051 admissions

In [5]:
data_1 = icustay_details.copy()
print("Number of patients: ", data_1['subject_id'].nunique())
print("Number of icu stays/admissions: ", data_1['icustay_id'].nunique())

Number of patients:  46428
Number of icu stays/admissions:  61051


## Patient/ICU stay Filtering
1. Filter for the first ICU admission of each patient
2. Exclude patients from NICU/PICU
3. Filter for ICU stays that were at least MIN_WINDOW_LENGTH long
4. Exclude patients with data recordes for less than MIN_WINDOW_LENGTH

### 1. Filter for the first ICU admission of each patient
We included only the first admission of each patient in the ICU, which resulted in each patient having only one ICU admission.

In [6]:
data_2 = data_1.copy()
#data_2 = data_2[data_2['first_icu_stay_current_hosp'] == True]
data_2 = data_2[data_2['first_icu_stay_patient'] == True]

Test: Each patient should have only one ICU stayd and its respecitve hospital admission

In [7]:
print("Number of patients: ", data_2['subject_id'].nunique())
print("Number of admissions: ", data_2['hadm_id'].nunique())
print("Number of ICU stays: ", data_2['icustay_id'].nunique())

Number of patients:  46428
Number of admissions:  46428
Number of ICU stays:  46428


### 2. Exclude patients from NICU/PICU
Patients admitted to the neonatal intensive care unit (NICU) and pediatric
intensive care unit (PICU) were excluded.

In [8]:
data_2 = data_2[data_2.first_careunit != "NICU"]
data_2 = data_2[data_2.first_careunit != "PICU"]

TEST: It should be 38566 patients/icu stays

In [9]:
print("Number of patients: ", data_2['subject_id'].nunique())
print("Number of ICU stays: ",data_2['icustay_id'].nunique())

Number of patients:  38566
Number of ICU stays:  38566


In [10]:
data_2[["intime", "outtime", "los_icu", "deathtime_icu", "label_death_icu"]].head(3)

intime             outtime   los_icu deathtime_icu  \
1 2101-10-20 19:10:11 2101-10-26 20:43:09  6.064560           NaT   
2 2191-03-16 00:29:31 2191-03-17 16:46:31  1.678472           NaT   
4 2175-05-30 21:30:54 2175-06-03 13:39:54  3.672917           NaT   

   label_death_icu  
1                0  
2                0  
4                0

### 3. Filter for ICU stays that were at least window lenght

In [11]:
data_3 = data_2.copy()
data_3 = data_3[data_3.los_icu >= MIN_WINDOW_LENGTH/24.0]   # FILTERING PATIENTS FOR AT LEAST THE WINDOW LENGTH

TEST: It should be 20396 patients/icu stays

In [12]:
print("Number of patients: ", data_3['subject_id'].nunique())
print("Number of icu stays: ", data_3['icustay_id'].nunique())

Number of patients:  20396
Number of icu stays:  20396


Temporary results of filtering

In [13]:
filtered_icustay_ids = pd.DataFrame(data_3['icustay_id'].unique(), columns=['icustay_id'])

### 4. Exclude patients with data recorded for less than MIN_WINDOW_LENGTH
Excluded patients for whom the duration between the first and last observations of vital signs and laboratory tests was less than MIN_WINDOW_LENGTH, i.e. first_recorded_value - intime <= MIN_WINDOW_LENGTH. The duration was calculated as the last timestamp minus the first timestamp in the chartevents/labevents table.

In [14]:
# Drop measurements with no belonging icustay_id
pivoted_vital = pivoted_vital.dropna(subset=['icustay_id'])
pivoted_lab = pivoted_lab.dropna(subset=['icustay_id'])

# Leave only relevant columns
vital_colums = ['icustay_id', 'charttime', 'heartrate', 'sysbp', 'diasbp', 'meanbp', 'resprate', 'tempc', 'spo2']
pivoted_vital = pivoted_vital[vital_colums]
lab_columns = ['icustay_id', 'charttime', 'albumin', 'bun', 'bilirubin', 'lactate', 'bicarbonate', 'bands', 'chloride', 'creatinine', 'glucose',
        'hemoglobin', 'hematocrit', 'platelet', 'potassium', 'ptt', 'sodium', 'wbc']
pivoted_lab = pivoted_lab[lab_columns]

# Cast icustay_id types to int
pivoted_vital['icustay_id'] = pivoted_vital['icustay_id'].astype(int)
pivoted_lab['icustay_id'] = pivoted_lab['icustay_id'].astype(int)

# Keep only values of patients in previously filtered icustay_ids in labs and vitals
pivoted_vital = pivoted_vital.merge(filtered_icustay_ids, on='icustay_id', how='right').drop_duplicates()
pivoted_lab = pivoted_lab.merge(filtered_icustay_ids, on='icustay_id', how='right').drop_duplicates()

Test: Number of ICU stays in vitals and labs should be the same as the filtered ones above - 20396

In [15]:
print("Number of ICU stays in pivoted_vital_filtered: ", pivoted_vital['icustay_id'].nunique())
print("Number of ICU stays in pivoted_lab_filtered: ", pivoted_lab['icustay_id'].nunique())

Number of ICU stays in pivoted_vital_filtered:  20396
Number of ICU stays in pivoted_lab_filtered:  20396


In [16]:
# Min of each lab and vitals
icustay_ids_charttime_min_lab = pivoted_lab[["icustay_id", "charttime"]][pivoted_lab.groupby("icustay_id")["charttime"].rank(ascending=1,method='dense') == 1]
icustay_ids_charttime_min_vital = pivoted_vital[["icustay_id", "charttime"]][pivoted_vital.groupby("icustay_id")["charttime"].rank(ascending=1,method='dense') == 1]
# Min of both combined
icustay_ids_charttime_min_vital_lab = pd.concat([icustay_ids_charttime_min_lab, icustay_ids_charttime_min_vital], ignore_index=True)
icustay_ids_charttime_min_vital_lab = icustay_ids_charttime_min_vital_lab[["icustay_id", "charttime"]][icustay_ids_charttime_min_vital_lab.groupby("icustay_id")["charttime"].rank(ascending=1,method='dense') == 1]

# Max of each lab and vitals
icustay_ids_charttime_max_lab = pivoted_lab[["icustay_id", "charttime"]][pivoted_lab.groupby("icustay_id")["charttime"].rank(ascending=0,method='dense') == 1]
icustay_ids_charttime_max_vital = pivoted_vital[["icustay_id", "charttime"]][pivoted_vital.groupby("icustay_id")["charttime"].rank(ascending=0,method='dense') == 1]
# Max of both combined
icustay_ids_charttime_max_vital_lab = pd.concat([icustay_ids_charttime_max_lab, icustay_ids_charttime_max_vital], ignore_index=True)
icustay_ids_charttime_max_vital_lab = icustay_ids_charttime_max_vital_lab[["icustay_id", "charttime"]][icustay_ids_charttime_max_vital_lab.groupby("icustay_id")["charttime"].rank(ascending=0,method='dense') == 1]

In [17]:
# Find for which icustay_ids there exist at least MIN_WINDOW_LENGTH of data
icustay_ids_vital_lab_charttime_min_max = pd.concat([icustay_ids_charttime_max_vital_lab, icustay_ids_charttime_min_vital_lab], ignore_index=True)
time_window = timedelta(days=0, seconds=0, microseconds=0, milliseconds=0, minutes=0, hours=MIN_WINDOW_LENGTH, weeks=0)
is_time_diff_bigger_window_lab = icustay_ids_vital_lab_charttime_min_max.groupby(['icustay_id'])['charttime'].transform(lambda x: (x.max()-x.min())) >= time_window

icustay_ids_vital_lab_charttime_min_max_filtered = icustay_ids_vital_lab_charttime_min_max[is_time_diff_bigger_window_lab]
print("Unique icu stays in icustay_ids_vital_lab_charttime_min_max_filtered after filtering", icustay_ids_vital_lab_charttime_min_max_filtered['icustay_id'].nunique())

# Keep only icustay ids for which at least MIN_WINDOW_LENGTH of data exists
icustay_ids_time_filtered = pd.DataFrame(icustay_ids_vital_lab_charttime_min_max_filtered['icustay_id'].unique(), columns=['icustay_id'])
print("Unique icu stays in icustay_ids_time_filtered: ", icustay_ids_time_filtered['icustay_id'].nunique())

Unique icu stays in icustay_ids_vital_lab_charttime_min_max_filtered after filtering 20200
Unique icu stays in icustay_ids_time_filtered:  20200


#### Final set of filtered icustay ids (filtered_icustay_ids)

In [18]:
filtered_icustay_ids = filtered_icustay_ids.merge(icustay_ids_time_filtered, on='icustay_id', how='inner').drop_duplicates()

Test: Final number of unique icustay ids should be 19414

In [19]:
print("Unique icu stays (final): ", filtered_icustay_ids['icustay_id'].nunique())

Unique icu stays (final):  20200


#### Create subset of all datasets (pivoted_lab, pivoted_vital, demographics) based on all exclusion criteria

In [20]:
demographics_filtered = data_3.merge(filtered_icustay_ids, on='icustay_id', how='right').drop_duplicates()
print("Number of ICU stays demographics: ", demographics_filtered['icustay_id'].nunique())

vital_filtered = pivoted_vital.merge(filtered_icustay_ids, on='icustay_id', how='right').drop_duplicates()
print("Number of ICU stays vitals: ", vital_filtered['icustay_id'].nunique())

lab_filtered = pivoted_lab.merge(filtered_icustay_ids, on='icustay_id', how='right').drop_duplicates()
print("Number of ICU stays labs: ", lab_filtered['icustay_id'].nunique())

Number of ICU stays demographics:  20200
Number of ICU stays vitals:  20200
Number of ICU stays labs:  20200


# DATA PREPARATION - ML format
Vital sign measurements were typically taken 0.5–1.5 times per hour for the MIMIC-III database, while laboratory measurements were typically taken 1–2 times per eight hours. Therefore, each vital sign variable was aggregated into a one-hour interval, whereas each laboratory variable was aggregated into an eight-hour interval. Repeated measurements in a single interval were aggregated by the median.

In [21]:
# Observation: The lab values and vital signs don't have the same starting time
vital_filtered[["icustay_id", "charttime"]][vital_filtered["icustay_id"] == 226799].sort_values("charttime").head(3), lab_filtered[["icustay_id", "charttime"]][lab_filtered["icustay_id"] == 226799].sort_values("charttime").head(3)

(         icustay_id           charttime
 3126719      226799 2153-07-31 08:00:00
 3126720      226799 2153-07-31 08:09:00
 3126721      226799 2153-07-31 08:10:00,
         icustay_id           charttime
 314037      226799 2153-07-30 23:27:00
 314038      226799 2153-07-30 23:33:00
 314039      226799 2153-07-31 01:26:00)

### Align time of entries of Labs & Vitals
Make sure that the vital & lab measurements of each patient start and end at the same time (so that both input time frames are ending up in the same timeframe) - The code below adds the same time steps with NaN values.

In [22]:
vital_filtered = vital_filtered.merge(lab_filtered[['icustay_id', 'charttime']], on=['icustay_id', 'charttime'], how='outer').drop_duplicates()
print("Number of ICU stays in lab_filtered: ", vital_filtered['icustay_id'].nunique())
lab_filtered = lab_filtered.merge(vital_filtered[['icustay_id', 'charttime']], on=['icustay_id', 'charttime'], how='outer').drop_duplicates()
print("Number of ICU stays in lab_filtered: ", lab_filtered['icustay_id'].nunique())

Number of ICU stays in lab_filtered:  20200
Number of ICU stays in lab_filtered:  20200


In [23]:
# Test: Now both, lab measurements and vital signs, should start at the same time (additional rows with NaN values).
vital_filtered[vital_filtered["icustay_id"] == 226799].sort_values("charttime").head(3), lab_filtered[lab_filtered["icustay_id"] == 226799].sort_values("charttime").head(3)

(         icustay_id           charttime  heartrate  sysbp  diasbp  meanbp  \
 4581051      226799 2153-07-30 23:27:00        NaN    NaN     NaN     NaN   
 4581052      226799 2153-07-30 23:33:00        NaN    NaN     NaN     NaN   
 4581053      226799 2153-07-31 01:26:00        NaN    NaN     NaN     NaN   
 
          resprate  tempc  spo2  
 4581051       NaN    NaN   NaN  
 4581052       NaN    NaN   NaN  
 4581053       NaN    NaN   NaN  ,
         icustay_id           charttime  albumin   bun  bilirubin  lactate  \
 314037      226799 2153-07-30 23:27:00      2.6  14.0        0.9      NaN   
 314038      226799 2153-07-30 23:33:00      NaN   NaN        NaN      4.7   
 314039      226799 2153-07-31 01:26:00      NaN   NaN        NaN      3.5   
 
         bicarbonate  bands  chloride  creatinine  glucose  hemoglobin  \
 314037         11.0    1.0     117.0         1.1    150.0        13.1   
 314038          NaN    NaN       NaN         NaN      NaN         NaN   
 314039      

### Resample Vital Signs

In [24]:
vital_resampled = vital_filtered.copy()

# Resample from the end of the time series (how="last")
vital_resampled = vital_resampled.assign(charttime=vital_resampled.charttime.dt.round('H'))
#vital_resampled = vital_resampled.set_index('charttime').groupby('icustay_id').resample('1H', origin="end").median().drop(['icustay_id'], axis = 1).reset_index()
# Resample from the beginning of the time series
vital_resampled = vital_resampled.set_index('charttime').groupby('icustay_id').resample('1H', origin="start").median().drop(['icustay_id'], axis = 1).reset_index()

# Forward and backwards fill (use lambda function instead of directly applying it to groupby otherwise results from one group are carreid forward to another group...BAD)
# Fill NaNs (-1)
vital_col = vital_resampled.columns.drop(['icustay_id', 'charttime'])
vital_resampled = vital_resampled.set_index(['icustay_id', 'charttime']).groupby('icustay_id')[vital_col].transform(lambda x: x.ffill().bfill()).fillna(-1).reset_index()
#.fillna(value=vital_resampled[vital_columns].mean())#.fillna(0)#.fillna(-1)

print(vital_filtered[vital_filtered["icustay_id"]==229633].tail(9))
print(vital_resampled[vital_resampled["icustay_id"]==229633].tail(3))
print(vital_resampled.isnull().sum().sum())

         icustay_id           charttime  heartrate  sysbp  diasbp  meanbp  \
4673939      229633 2147-02-08 12:24:00        NaN    NaN     NaN     NaN   
4673940      229633 2147-02-08 13:26:00        NaN    NaN     NaN     NaN   
4673941      229633 2147-02-08 15:07:00        NaN    NaN     NaN     NaN   
4673942      229633 2147-02-09 02:31:00        NaN    NaN     NaN     NaN   
4673943      229633 2147-02-09 07:35:00        NaN    NaN     NaN     NaN   
4673944      229633 2147-02-09 08:09:00        NaN    NaN     NaN     NaN   
4673945      229633 2147-02-09 15:46:00        NaN    NaN     NaN     NaN   
4673946      229633 2147-02-10 01:05:00        NaN    NaN     NaN     NaN   
4673947      229633 2147-02-11 03:07:00        NaN    NaN     NaN     NaN   

         resprate  tempc  spo2  
4673939       NaN    NaN   NaN  
4673940       NaN    NaN   NaN  
4673941       NaN    NaN   NaN  
4673942       NaN    NaN   NaN  
4673943       NaN    NaN   NaN  
4673944       NaN    NaN   NaN 

In [25]:
vital_resampled["icustay_id"].nunique()

20200

Test for classification - This must run error free for running the code later

In [26]:
test = vital_resampled.copy()
test = test.groupby("icustay_id").head(48)
print(test.head(3))
print(test.groupby(["icustay_id"])["charttime"].nunique().unique())

   icustay_id           charttime  heartrate  sysbp  diasbp  meanbp  resprate  \
0      200003 2199-08-02 18:00:00      132.0  106.0    68.0    73.0      25.0   
1      200003 2199-08-02 19:00:00      132.0  106.0    68.0    73.0      25.0   
2      200003 2199-08-02 20:00:00      119.0   91.0    49.0    58.0      35.0   

       tempc  spo2  
0  39.555554  97.0  
1  39.555554  97.0  
2  39.555554  97.0  
[48]


### Resample Laboratory Measurements
Added bfill to make sure that those values are not NaN

In [ ]:
lab_resampled = lab_filtered.copy()
# Cut out minutes and hours, so that the resampling of the 8h takes the same time span as the 1h samples (for vitals)
lab_resampled = lab_resampled.assign(charttime=lab_resampled.charttime.dt.round('H'))
# Resample from the end of the time series 
#lab_resampled = lab_resampled.set_index('charttime').groupby('icustay_id').resample('8h', origin="end").median().drop(['icustay_id'], axis = 1).reset_index()
lab_resampled = lab_resampled.set_index('charttime').groupby('icustay_id').resample('8h', origin="start").median().drop(['icustay_id'], axis = 1).reset_index()

# Forward and backwards fill (use transform instead of direct groupby otherwise results from one group are carreid forward to another group...BAD)
# Fill NaNs (-1 or 0 or mean!?)
lab_col = lab_resampled.columns.drop(['icustay_id', 'charttime'])
lab_resampled = lab_resampled.set_index(['icustay_id', 'charttime']).groupby('icustay_id')[lab_col].transform(lambda x: x.ffill().bfill()).fillna(-1).reset_index()

print(lab_filtered[lab_filtered["icustay_id"]==229633].tail(9))
print(lab_resampled[lab_resampled["icustay_id"]==229633].tail(3))
print(lab_resampled.isnull().sum().sum())


Test for classification  - This must run error free for running the code later

In [ ]:
test = lab_resampled.copy()
test = test.groupby("icustay_id").head(6)
print(test.head(3))
print(test.groupby(["icustay_id"])["charttime"].nunique().unique())

## Some Statistical Information

### Demographics

In [ ]:
demographics_filtered.describe()

In [ ]:
demographics_filtered[demographics_filtered["label_death_icu"]==1].describe()

In [ ]:
demographics_filtered[demographics_filtered["label_death_icu"]==0].describe()

### Vital Signs

In [ ]:
vital_resampled.describe()

### Lab Measurements

In [ ]:
lab_resampled.describe()

## Save Data

### Write Final Datasets into Postgres

In [ ]:
engine = create_engine('postgresql://postgres:postgres@localhost:5433/mimic')

demographics_filtered.to_sql(f'demographics_min{MIN_WINDOW_LENGTH:d}h', engine, if_exists='replace')
vital_resampled.to_sql(f'vital_resampled_min{MIN_WINDOW_LENGTH:d}h', engine, if_exists='replace')
lab_resampled.to_sql(f'lab_resampled_min{MIN_WINDOW_LENGTH:d}h', engine, if_exists='replace')

### Write Final Datasets into Pickle files (alternative to postgres)

In [ ]:
demographics_filtered.to_pickle(f'demographics_min{MIN_WINDOW_LENGTH:d}h.pickle')
vital_resampled.to_pickle(f'vitals_min{MIN_WINDOW_LENGTH:d}h.pickle')
lab_resampled.to_pickle(f'labs_min{MIN_WINDOW_LENGTH:d}h.pickle')